# Package builds
name: Publish to PyPI on Release

on:
  release:
    types: ["published"]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: PyPI Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable .[dev]

    - name: Build wheel
      run: |
        python -m build --wheel
        twine check dist/*
    
    - name: Upload to Test PyPI 
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
