name: Publish to PyPI on Release w/ uv

on:
  release:
    types: ["published"]

jobs:
  publish:
    name: uv build and PyPI Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: |
        uv pip install -r pyproject.toml --extra dev

    - name: Build
      run: |
        uv build
    
    - name: Upload to Test PyPI
      run: |
        uv publish --index testpypi --token ${{ secrets.UV_PYPI_TOKEN }}